name =input("What is your name==>")
surname =input("What is your surname==>")
year =input("year==>")
idstudent =input("What is your idstudent==>")
print("")
print(name)
print(surname)
print(year)
print(idstudent)