a =input("Input Number [1]")
b =input("Input Number [2]")
c =input("Input Number [3]")
d =input("Input Number [4]")
e =input("Input Number [5]")
a1 = float (a)
a2 = complex (a)
print("Float of "+a +" Equal",+a1)
print("Complex of "+a +" Equal",+a2)
b1 = float (b)
b2 = complex (b)
print("Float of "+b +" Equal",+b1)
print("Complex of "+b +" Equal",+b2)
c1 = float (c)
c2 = complex (c)
print("Float of "+c +" Equal",+c1)
print("Complex of "+c +" Equal",+c2)
d1 = float (d)
d2 = complex (d)
print("Float of "+d +" Equal",+d1)
print("Complex of "+d +" Equal",+d2)
e1 = float (e)
e2 = complex (e)
print("Float of "+e +" Equal",+e1)
print("Complex of "+e +" Equal",+e2)